DROP TABLE facttable CASCADE;
DROP TABLE dateID CASCADE;
DROP TABLE articleID CASCADE;
DROP TABLE shopID CASCADE;
DROP TABLE country CASCADE;
DROP TABLE region CASCADE;
DROP TABLE city CASCADE;
DROP TABLE shop CASCADE;
DROP TABLE article CASCADE;
DROP TABLE productgroup CASCADE;
DROP TABLE productfamily CASCADE;
DROP TABLE productcategory CASCADE;

